import { BsFacebook, BsTwitter, BsInstagram, BsLinkedin } from "react-icons/bs";

export const images = [
  {
    src: "/assets/img/banner/dea037v3_lg_1_2_banner.jpg",
    logo: "/assets/img/eventos/dea037v3_1_2_logo.png",
    ticket: "/assets/img/logos/ico-ticket.png",
    title: "Gran Espectáculo de Tango",
    tipoConcierto: "Concierto / Presencial",
    date: "24 Setiembre 2023",
    button: "Ver más",
  },
  {
    src: "/assets/img/banner/tro022_lg_1_2_banner.jpg",
    logo: "/assets/img/eventos/tro022_1_2_logo.png",
    ticket: "/assets/img/logos/ico-ticket.png",
    title: "El Gran Combo de Puerto Rico",
    tipoConcierto: "Concierto / Presencial",
    date: "21 Setiembre 2023",
    button: "Ver más",
  },
  {
    src: "/assets/img/banner/ven032_lg_1_2_banner.jpg",
    logo: "/assets/img/eventos/ven032_1_2_logo.png",
    ticket: "/assets/img/logos/ico-ticket.png",
    title: "Rels B",
    tipoConcierto: "Concierto / Presencial",
    date: "24 Setiembre 2023",
    button: "Ver más",
  },
];

export const events = [
  {
    id: "1",
    src: "/assets/img/eventos/all003_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "2",
    src: "/assets/img/eventos/bss001_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "3",
    src: "/assets/img/eventos/cal049_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "4",
    src: "/assets/img/eventos/eli016_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "5",
    src: "/assets/img/eventos/eli017_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "6",
    src: "/assets/img/eventos/ico003_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "7",
    src: "/assets/img/eventos/ics035_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "8",
    src: "/assets/img/eventos/ics036_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "9",
    src: "/assets/img/eventos/nra001_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "10",
    src: "/assets/img/eventos/nra002_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "11",
    src: "/assets/img/eventos/vas013_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "12",
    src: "/assets/img/eventos/ven028_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "13",
    src: "/assets/img/eventos/dea037_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
  {
    id: "14",
    src: "/assets/img/eventos/ali020_calugalistado.jpg",
    ticket: "/assets/img/logos/ico-ticket.png",
    cityName: "Los Ángeles, CA",
    nameEvent: "All Night Live - Los Angeles (Los Ángeles)",
    dateTimeStart: "25 Sep 2021  9am ",
    dateTimeEnd: "26 Sep 2021  8pm",
    priceTicket: "$10 USD",
  },
];

export const featured = [
  {
    id: 1,
    imagePrincipal:
      "/assets/img/info/centroayuda_lg_calugalateral_2.jpg",
    title: "Centro de Ayuda",
  },
  {
    id: 2,
    imagePrincipal: "/assets/img/info/punto_caluga.jpg",
    title: "Punto de Ventas",
  },
  {
    id: 3,
    imagePrincipal: "/assets/img/info/rimac_calugadestacado.jpg",
    title: "Seguros",
  },
];

export const footerList = [
  {
    id: 1,
    title: "Acerca de Nosotros",
    linkToPage: "",
  },
  {
    id: 2,
    title: "Términos y condiciones",
    linkToPage: "",
  },
  {
    id: 3,
    title: "Política de compra",
    linkToPage: "",
  },
  {
    id: 4,
    title: "Política de privacidad y cookies",
    linkToPage: "",
  },
  {
    id: 5,
    title: "Revisa tu boleta",
    linkToPage: "",
  },
];

export const footerSocial = [
  {
    id: 1,
    icon: <BsFacebook size={25}/>,
    title: 'Facebook',
  },
  {
    id: 2,
    icon: <BsTwitter size={25}/>,
    title: 'Twitter',
  },
  {
    id: 3,
    icon: <BsInstagram size={25}/>,
    title: 'Instagram',

  },
  {
    id: 4,
    icon: <BsLinkedin size={25}/>,
    title: 'Linkedin',
  },
];
